name: Android CI (Authenticated)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Build
        env:
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: ${{ secrets.MAVEN_CENTRAL_STAGING_PROFILE_ID }}
          MAVEN_CENTRAL_SIGNING_KEY_ID:     ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          CI_GITHUB_ACCESS_TOKEN:           ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
        run: .ci/ci-main.sh normal

      - name: Upload demo APK
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: always()
        with:
          name: org.librarysimplified.r2.demo-debug.apk
          path: ./org.librarysimplified.r2.demo/build/outputs/apk/debug/org.librarysimplified.r2.demo-debug.apk
